# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_claim_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
