# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_auto_20160328_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
