# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_auto_20160328_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
