# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 19:00
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_claim_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='title',
            new_name='name'
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='claimcontent',
            new_name='content'
        )
    ]
