# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_auto_20160905_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='contrib_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
