# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0012_auto_20160905_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='affirmations',
        ),
        migrations.AddField(
            model_name='affirmations',
            name='claim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Claim'),
        ),
        migrations.AddField(
            model_name='affirmations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
