# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_auto_20160905_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affirmations',
            new_name='Affirmation',
        ),
    ]
