# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_auto_20160905_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affirmation',
            old_name='claim_id',
            new_name='claim',
        ),
        migrations.RenameField(
            model_name='affirmation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='contrib_user_id',
            new_name='contrib_user',
        ),
    ]
