# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0015_auto_20160905_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affirmation',
            old_name='claim',
            new_name='affirmed_claim',
        ),
        migrations.RenameField(
            model_name='affirmation',
            old_name='user',
            new_name='affirming_user',
        ),
        migrations.AlterUniqueTogether(
            name='affirmation',
            unique_together=set([('affirming_user', 'affirmed_claim')]),
        ),
    ]
