# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0018_auto_20160914_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affirmation',
            old_name='claim_id',
            new_name='claim',
        ),
        migrations.RenameField(
            model_name='affirmation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='affirmation',
            unique_together=set([('claim', 'user')]),
        ),
    ]
