# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_auto_20160918_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='creator',
            new_name='creator_user',
        ),
    ]
