# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0022_auto_20161004_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentPremise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='argument',
            name='premise_claims',
        ),
        migrations.AlterField(
            model_name='argument',
            name='supported_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_arguments', to='claims.Claim'),
        ),
        migrations.AddField(
            model_name='argumentpremise',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Argument'),
        ),
        migrations.AddField(
            model_name='argumentpremise',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Claim'),
        ),
    ]
