# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0025_argument_argumentpremise'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='premise_claims',
            field=models.ManyToManyField(through='claims.ArgumentPremise', to='claims.Claim'),
        ),
    ]
