# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0026_argument_premise_claims'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='argument',
            unique_together=set([('name', 'supported_claim')]),
        ),
        migrations.AlterUniqueTogether(
            name='argumentpremise',
            unique_together=set([('argument', 'claim')]),
        ),
    ]
