# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_auto_20160328_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='authority',
            field=models.IntegerField(default=0),
        ),
    ]
