# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-25 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0004_standarduser_affirms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='affirms',
        ),
    ]
